### ISSUE TITLE
Create new palette button doesn't work

### ISSUE THREAD

**Issue by outerpress** [genevievecurry/paint-library-app#64]
Clicked "create new palette" and button disappeared/offered no other action.

Browser: Firefox 97.0
User: Me! :)

To reproduce:
* Open [Duochrome Cabo Blue](https://www.paintlibrary.art/paint/ae63f5e2-fb86-46c8-a3a4-0c9c24f6f9c0/duochrome-cabo-blue)
* Click add to palette
* Click create new palette

Other notes:

Tested with other colors, same result

There was a console error when I first ran through, haven't been able to reproduce it though:
<img width="389" alt="Screen Shot 2022-02-26 at 10 21 34 AM" src="https://user-images.githubusercontent.com/2536801/155854729-97c5f08a-cc02-4aea-bd2d-ff62aca62ebc.png">

**Comment by genevievecurry** [comment]
Thanks @outerpress! This should be resolved now :)

**Comment by outerpress** [comment]
Confirmed resolved!
